# Generated by Django 3.1.5 on 2021-07-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stick_protocol', '0009_auto_20210703_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptionsenderkey',
            name='chainId',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
