# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

pod 'StickySignalProtocolC', '1.0.2'
pod 'SimpleKeychain', :modular_headers => true
pod 'SignalArgon2'
pod 'CryptoSwift'
pod 'SQLCipher', ">= 4.0.1", :modular_headers => true
pod 'YapDatabase/SQLCipher', :git => 'https://github.com/signalapp/YapDatabase.git', branch: 'signal-release', :modular_headers => true
pod 'Mantle', :modular_headers => true
#pod 'CocoaLumberjack'

target 'StickProtocol' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for StickProtocol

  target 'StickProtocolTests' do
    # Pods for testing
  end
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              # Needed for building for simulator on M1 Macs
              config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
          end
      end
  end
end